import { checkDataLoginForm, checkDataRegistrationForm } from '../services/validation';

// one metod
/* test('checking form login', () => {
    expect(checkDataLoginForm('test@email.ru', '1!Atestpassword')).toBe('Successfully');
}); */

describe('Checking form login', () => {
    const testCase = [
        {
            email: '1@mail1.ru',
            password: 'Aqswdefr1!',
            expected: JSON.stringify({ email: true, password: true }),
        },
        {
            email: '1@m ail2.ru',
            password: 'Aqswdefr1!',
            expected: JSON.stringify({ email: false, password: true }),
        },
        {
            email: 'test@email3.ru ',
            password: 'Aqswdefr1!',
            expected: JSON.stringify({ email: false, password: true }),
        },
        {
            email: ' test@email4.ru',
            password: 'Aqswdefr1!',
            expected: JSON.stringify({ email: false, password: true }),
        },
        {
            email: 'test@email5.ru',
            password: 'qswdefre',
            expected: JSON.stringify({ email: true, password: false }),
        },
        {
            email: 'test@email6.ru',
            password: 'qswdefre1',
            expected: JSON.stringify({ email: true, password: false }),
        },
        {
            email: 'test@email7.ru',
            password: 'qswdefre1!',
            expected: JSON.stringify({ email: true, password: false }),
        },
        {
            email: 'test@email8.ru ',
            password: 'qswdefre1',
            expected: JSON.stringify({ email: false, password: false }),
        },
        {
            email: '',
            password: '',
            expected: JSON.stringify({ email: false, password: false }),
        },
    ];
    testCase.forEach((test) => {
        it(`${test.email}`, () => {
            const res = checkDataLoginForm(test.email, test.password);
            expect(JSON.stringify(res)).toBe(test.expected);
        });
    });
});

describe('Checking form registration', () => {
    const testCase = [
        {
            email: 'test@email1.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email2.ru ',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: false,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email3.ru ',
            password: 'Aqswdefr1',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: false,
                password: false,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email4.ru',
            password: 'Aqswdefr1!',
            nameUser: 'J!',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: false,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email5.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: '',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: false,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email6.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2015-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: false,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email7.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: '',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: false,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email8.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: '',
            addressPostalCode: '123A15',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: false,
                addressPostalCode: true,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email9.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A156548',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: false,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email10.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: false,
                addressCountry: true,
            }),
        },
        {
            email: 'test@email11.ru',
            password: 'Aqswdefr1!',
            nameUser: 'Jonh',
            lastNameUser: 'Smith',
            dateBirth: '2010-01-01',
            addressStreet: 'Brooklyn',
            addressCity: 'New York',
            addressPostalCode: '123A15',
            addressCountry: '',
            expected: JSON.stringify({
                email: true,
                password: true,
                nameUser: true,
                lastNameUser: true,
                dateBirth: true,
                addressStreet: true,
                addressCity: true,
                addressPostalCode: true,
                addressCountry: false,
            }),
        },
        {
            email: 'test@ email1.ru',
            password: 'Aqswdefr!',
            nameUser: 'Jonh!',
            lastNameUser: 'Smith',
            dateBirth: '2016-01-01',
            addressStreet: '',
            addressCity: 'New York',
            addressPostalCode: '123A1',
            addressCountry: 'USA',
            expected: JSON.stringify({
                email: false,
                password: false,
                nameUser: false,
                lastNameUser: true,
                dateBirth: false,
                addressStreet: false,
                addressCity: true,
                addressPostalCode: false,
                addressCountry: true,
            }),
        },
    ];
    testCase.forEach((test) => {
        it(`data: ${test.email}`, () => {
            const res = checkDataRegistrationForm(
                test.email,
                test.password,
                test.nameUser,
                test.lastNameUser,
                test.dateBirth,
                test.addressStreet,
                test.addressCity,
                test.addressPostalCode,
                test.addressCountry
            );
            expect(JSON.stringify(res)).toBe(test.expected);
        });
    });
});
